//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `UserService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.apache.dubbo.rpc.protocol.ice.user;

/**
 * @hidden
 */
public class _UserServicePrxI extends com.zeroc.Ice._ObjectPrxI implements UserServicePrx {
    /**
     * @hidden
     */
    public static final long serialVersionUID = 0L;
}
