//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.2
//
// <auto-generated>
//
// Generated from file `DemoService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package org.apache.dubbo.rpc.protocol.ice.demo;

/** @hidden */
public class _DemoServicePrxI extends com.zeroc.Ice._ObjectPrxI implements DemoServicePrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
